# Broker client configuration file
host: "localhost" #ClusterURL
port: 1883
clientId: "virtualAADIProvider"
authentication:
    token:
topics:
    - publishTopic: "smartocean/pd1/austevoll-nord"
      source: /home/keila/smartoceanplatform/pd1-sampledata/SFI_Austevoll_NordDestination/
      # https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt-operations/publish/#quality-of-service-qos
      qos: 1 # 0 - AT_MOST_ONCE  | 1 - AT_MOST_ONCE | 2 - EXACTLY_ONCE
