host: "127.0.0.1"
port: 1883 #websocket 1888
clientId: "virtualAADIProvider"
authentication:
    token:
topics:
    - publishTopic: "smartocean/pd1/austevoll-nord"
      source: "data"
      # https://hivemq.github.io/hivemq-mqtt-client/docs/mqtt-operations/publish/#quality-of-service-qos
      qos: 2 # 0 - AT_MOST_ONCE  | 1 - AT_MOST_ONCE | 2 - EXACTLY_ONCE
